nelmio_api_doc:
    documentation:
        info:
            title: API
            description: LIFT-TEST
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - /api/v1
        #- ^/api(?!/doc$) # Accepts routes under /api except /api/doc
